source: ./source
destination: ./_deploy
permalink: /:year/:month/:title/
highlighter: pygments

assets:
  dirname: .
  baseurl: /
  sources:
    - _assets
    - _assets/css
    - _assets/js
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
jekyll-press:
  exclude: ['robots.txt']

url: http://benedfit.com
title: Ben Edwards, a web designer and developer
description: Web Designer, Developer, and Ultimate Knot-tier&trade;. Banging on about Responsive Design, Web Standards. Defintely not good at tests.
authorName: Ben Edwards
authorUrl: https://plus.google.com/+benedfit
authorImage: https://www.gravatar.com/avatar/f192577527e4541aa21b501fb43ee68c?s=200