source: ./source
destination: ./_deploy
permalink: /:year/:month/:title/

assets:
  dirname: .
  baseurl: /
  sources:
    - _assets
    - _assets/css
    - _assets/js
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
jekyll-press:
  exclude: ['robots.txt']

url: http://benedfit.com
title: Ben Edwards, a web designer and developer
description: Web Designer, Developer, and Ultimate Knot-tier&trade;. Technical Consultant at Netcel. Banging on about Responsive Design, Web Standards and all that stuff
logo: <span>Benedfi</span>t
author: Ben Edwards