source: ./source
destination: ./_deploy
permalink: /:year/:month/:title
excerpt_separator: "<!--/excerpt-->"

assets:
  dirname: .
  baseurl: /
  sources:
    - _assets
    - _assets/css
    - _assets/js
  cachebust: none
  js_compressor: none
  css_compressor: none
  gzip: false

url: http://benedfit.com
title: Ben Edwards, a web designer and developer
description: Ben Edwards, a web designer and developer
logo: Benedfit