source: ./source
destination: ./_deploy
keep_files: [css]
permalink: /:year/:month/:title
excerpt_separator: "<!--/excerpt-->"

assets:
  dirname: js
  sources:
    - _js
  cachebust: none
  compress:
    js: uglifier
    css: sass
  gzip: false

url: http://benedfit.com
title: Ben Edwards, a web designer and developer
description: Ben Edwards, a web designer and developer
logo: Benedfit