source: ./source
destination: ./_deploy
permalink: /:year/:month/:title

assets:
  dirname: .
  baseurl: /
  sources:
    - _assets
    - _assets/css
    - _assets/js
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
jekyll-press:
  exclude: ['robots.txt']

url: http://benedfit.com
title: Ben Edwards, a web designer and developer
description: Ben Edwards, a web designer and developer
logo: Benedfit