permalink: /:year/:month/:title/
assets:
  dirname: .
  baseurl: /
  sources:
    - _assets
    - _assets/css
    - _assets/fonts
    - _assets/img
    - _assets/js
  js_compressor: yui
  css_compressor: yui
  cachebust: none
jekyll-press:
  exclude: ['*.txt']
url: https://benedfit.com
title: Ben Edwards, a Web Designer and Developer
description: Ultimate Knot-tier and Head of Front-end Development at Clock. Banging on about Responsive Design, Web Standards
tilecolor: #000000
authorname: Ben Edwards
authoremail: hello@benedfit.com
authorhandle: benedfit
authorurl: https://plus.google.com/+benedfit
authorimage: https://www.gravatar.com/avatar/f192577527e4541aa21b501fb43ee68c?s=200